apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: every-ten-minutes
  namespace: openshift-adp
spec:
  schedule: '*/10 * * * *'
  template:
    storageLocation: <backupstoragelocation - velero-dpa-1>
    includedNamespaces:
      - tekton
    excludedNamespaces:
      - openshift